manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rmwphd
      url-base: https://github.com/rmwphd
    - name: cdc-mkb
      url-base: https://github.com/cdc-mkb # name: zmk, revision: mouse-pim447
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
  self:
    path: config
