manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: rmwphd
      url-base: https://github.com/rmwphd
  projects:
    - name: zmk
      remote: rmwphd
      revision: main
      import: app/west.yml
  self:
    path: config
